#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 17 12:25:25 2020

@author: menglu
"""

import os
import gdal 
 

os.getcwd()
directoryPath = os.path.join(directoryPath, directoryName)
os.chdir("/Volumes/Seagate Expansion Drive" )
os.listdir()
rasterdir = "/Volumes/Seagate Expansion Drive/global"

imagearr = []
for i in range(4,5):
    mapdir = os.path.join(rasterdir,str(i),"laea","road_class_1_25.map")
    os.chdir(os.path.join(rasterdir,str(i),"laea"))
       
    gdal.Open(mapdir).ReadAsArray     
