#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 23 14:21:26 2020

@author: menglu
"""
 

import os
import gdal 
import numpy as np
import glob
 
import pandas as pd
os.getcwd() 
rasterdir = "/Users/menglu/Documents/R_default/utrecht/"
tif = glob.glob("/Users/menglu/Documents/R_default/utrecht/*.tif" )
 

   # plt.imshow(arr)
   # plt.show()
   # print(arr.shape)
np.save('/Users/menglu/Documents/Github/deep_learning/utroad2', np.array(gdal.Open(tif[0]).ReadAsArray()   ))
np.save('/Users/menglu/Documents/Github/deep_learning/utroad3', np.array(gdal.Open(tif[1]).ReadAsArray()   ))
np.save('/Users/menglu/Documents/Github/deep_learning/utroad4', np.array(gdal.Open(tif[2]).ReadAsArray()   ))
np.save('/Users/menglu/Documents/Github/deep_learning/utroad5', np.array(gdal.Open(tif[3]).ReadAsArray()   ))
#599,2225,2478,2504
# till 2634




